name: Deploy Docusaurus

on:
  push:
    branches:
      - main  # Exécute le workflow à chaque push sur "main"
  workflow_dispatch:  # Permet d'exécuter manuellement le workflow depuis GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Donne la permission d'écriture pour pousser sur gh-pages

    steps:
      - name: 🛎️ Checkout repository
        uses: actions/checkout@v3

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: |
          cd website
          npm install

      - name: 🚀 Build Docusaurus
        run: |
          cd website
          npm run build

      - name: 🌍 Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd website
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npm install -g gh-pages
          np
